### ISSUE TITLE
Can it be enabled in javascript?

### ISSUE THREAD

**Issue by ouweiya** [vscodeshift/material-ui-snippets#11]
Can it be enabled in javascript?
I have seen the source code, and I know how to open it, but why are you not going to do this?

**Comment by oliviertassinari** [comment]
@ouweiya Do you mean that you can't get the plugin work with your sources in JavaScript?

**Comment by ouweiya** [comment]
This is not my problem, it is this extension design problem.
Can you use it in javascript?

Activation language does not contain javascript

```json
package.json

"activationEvents": [
  "onLanguage:javascriptreact",
  "onLanguage:typescriptreact"
],
```

```js
extension.js

function activate(context) {
  for (const language of ['javascriptreact', 'typescriptreact']) {
    let lastOptions = null;
    let lastSnippets;
...
```

**Comment by ouweiya** [comment]
I don't know why the language server cannot be implemented in `makeStyles`

Don't know  `vscode-styled-components`  how to do it.
If we have a language server, we may not need to use snippets

const useStyles = makeStyles(() => ({
 ...
}));

**Comment by oliviertassinari** [comment]
The requirement on `javascriptreact` sounds expected.

**Comment by ouweiya** [comment]
why not?

```json
"activationEvents": [
    "onLanguage:javascript",
    "onLanguage:javascriptreact",
    "onLanguage:typescriptreact"
  ],
```

```js
function activate(context) {
  for (const language of ['javascript', 'javascriptreact', 'typescriptreact']) {
    let lastOptions = null
    let lastSnippets
```

**Comment by oliviertassinari** [comment]
cc @jedwards1211

**Comment by jedwards1211** [comment]
@ouweiya I have this in the README but probably it's easy to miss when you find and install an extension from VSCode (maybe I should make this extension show tips when first installed?)

> If you use JSX in .js files you will need to click on JavaScript in the bottom right corner of VSCode and Configure File Association for .js... to be JavaScript React.

I figured anyone who uses JSX in `.js` files will want to change the file association anyway for the sake of various other tools.
Does this work for you or do you need to leave the file association for `.js` as just JavaScript for some reason?

**Comment by jedwards1211** [comment]
On the other hand I guess the snippet names probably wouldn't conflict with any non-JSX tools in the JS-only context, so it might make sense to switch it on for JS.  @oliviertassinari what do you think?

**Comment by jedwards1211** [comment]
Personally, I wish no one had started a convention of using `.jsx`/`.tsx` extensions...

**Comment by oliviertassinari** [comment]
> I figured anyone who uses JSX in .js files will want to change the file association anyway for the sake of various other tools.

@jedwards1211 This is my understanding of the situation. But now that I look at my Visual Studio Code configuration, I see that I'm on the "JavaScript" mode 😆.

**Comment by ouweiya** [comment]
I have read the instructions very carefully, but changing the locale manually is a disaster for many files.
Of course, we can also configure the way to map the relationship, but it will cause new troubles.
![Snipaste_2020-04-14_01-21-55](https://user-images.githubusercontent.com/28357731/79143113-38b0fb80-7def-11ea-9ea8-0ac3134869ed.png)

Confusion of file distinction. Of course these are small problems,

The biggest problem is that making a specific configuration for JSX violates the entire ecology, which is a long-standing discussion.

https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904

**Comment by ouweiya** [comment]
I think the prejudice against jsx should be put down, because jsx is js, and eventually they will become `React.createElement ('div', null, 'Hello')`

**Comment by jedwards1211** [comment]
Hmmm I think I will go ahead and make this activate for js, you've convinced me.
