### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bestaps** [vscodeshift/material-ui-snippets#15]
[vscodeshift.material-ui-snippets-unresponsive.cpuprofile.txt](https://github.com/vscodeshift/material-ui-snippets/files/4705698/vscodeshift.material-ui-snippets-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `material-ui-snippets`
- Extension Version: `3.2.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

Extension is unresponsive. PFA, the cpu profile text file.

**Comment by jedwards1211** [comment]
@prem48science have you tried turning off automatic imports in the extension settings?

This was reported in #14 and turning off automatic imports is the only solution until https://github.com/microsoft/vscode/pull/97515 gets released.

**Comment by bestaps** [comment]
yes, I did turn off automatic imports, and problem is resolved. seems the only option. thanks for the support.

**Comment by jedwards1211** [comment]
Okay now in version 3.3.0 there are also commands you can use to insert the snippets; the commands will add the missing imports but you shouldn't have the same performance problems as with the completions.
