### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ansyahardi** [vscodeshift/material-ui-snippets#22]
- Issue Type: `Performance`
- Extension Name: `material-ui-snippets`
- Extension Version: `3.3.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.49.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ardiansyah\vscodeshift.material-ui-snippets-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jedwards1211** [comment]
I guess you found the performance tip in the readme?
