### ISSUE TITLE
performance issue take too much time to load and prevents other extensions to load.

### ISSUE THREAD

**Issue by ValeedAnjum** [vscodeshift/material-ui-snippets#27]
- Issue Type: `Bug`
- Extension Name: `material-ui-snippets`
- Extension Version: `3.3.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

**Comment by jedwards1211** [comment]
I published a new version (3.3.1) that activates the extension async.  Can you let me know if the problem still occurs with that version?  If so can you paste the Extension Host log or whatever error message you were seeing?

**Comment by ValeedAnjum** [comment]
it is working well with the new version 3.3.1
