### ISSUE TITLE
[SUGGESTION] Add Snippet for makeStyles

### ISSUE THREAD

**Issue by EliteMasterEric** [vscodeshift/material-ui-snippets#30]
The snippet `makeStyles` should add the following code:

```
const useStyles = makeStyles((theme) => ({

}));
```

Since I use this a lot, it would be a convenient snippet to add.

**Comment by jedwards1211** [comment]
I have commands for this in this extension, check it out! https://github.com/codemodsquad/material-ui-codemorphs, they're much more sophisticated than snippets can be
