### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by BanerjeeProdipta** [vscodeshift/material-ui-snippets#31]
- Issue Type: `Bug`
- Extension Name: `material-ui-snippets`
- Extension Version: `3.3.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jedwards1211** [comment]
Looks like you didn't paste...

**Comment by jedwards1211** [comment]
If you were having a performance problem or something, feel free to let me know :) I just need some details about what problem you were having
