### ISSUE TITLE
Aggregated imports

### ISSUE THREAD

**Issue by ma-pe** [vscodeshift/material-ui-snippets#4]
Hey there,

thanks a lot for creating this extension.

I am personally aggregating my imports as in:

```
import { LinearProgress, makeStyles, Typography } from "@material-ui/core";
```

Do you see a chance to extend the aggregated import instead of adding another import line?

**Comment by jedwards1211** [comment]
Sorry for the delay, for some reason I wasn't configured to watch my own project 😜
Yeah that's definitely possible!  I'll get working on it

**Comment by jedwards1211** [comment]
So in the **Import Paths** extension setting in this new version, select **top level**, and then it will always add your style of imports 👍

**Comment by ma-pe** [comment]
I love it! Many thanks 🙏
