### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Fullstack-WEB-Blockchain-Developer** [vscodeshift/material-ui-snippets#44]
- Issue Type: `Bug`
- Extension Name: `material-ui-snippets`
- Extension Version: `3.3.3`
- OS Version: `Windows_NT x64 10.0.18362`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jedwards1211** [comment]
What was happening?
