### ISSUE TITLE
Add missing components

### ISSUE THREAD

**Issue by flyingangel** [vscodeshift/material-ui-snippets#47]
Please add missing components snippets. For instance muiBox :

    <Box></Box>

List of useful components that I usually use :

https://material-ui.com/components/box/
https://material-ui.com/components/hidden/
https://material-ui.com/components/breadcrumbs/
https://material-ui.com/components/links/

**Comment by oliviertassinari** [comment]
https://material-ui.com/components/hidden/ is deprecated in v5, I don't think that we should include it

Missing:

- https://material-ui.com/components/stack/
