### ISSUE TITLE
MUI v5 changes

### ISSUE THREAD

**Issue by oliviertassinari** [vscodeshift/material-ui-snippets#49]
I'm opening this issue to notify the upcoming changes coming to the library:

- "Material-UI" become "MUI", we might not move the domain name to https://mui.com just yet.
- The logo and branding is changing, more information in an upcoming blog post
- `@material-ui/core` imports become `@mui/material`

**Comment by jedwards1211** [comment]
Just got back from a vacation, thanks for the heads up.  Are all of the component and property names finalized so that I could go ahead and release a new version of `material-ui-snippets`?

**Comment by j3ffx** [comment]
I'd love such an update since I work with the last version and thus got '@mui/material' imports, please keep me updated on the release :D

**Comment by jedwards1211** [comment]
@oliviertassinari please let me know when y'all are done making breaking changes to v5, people are begging me to support a beta version

**Comment by jedwards1211** [comment]
!@#$ing VSCode not supporting beta versions for extensions... 🙄

**Comment by jedwards1211** [comment]
Okay I released a separate `MUI Snippets` extension for v5:

https://github.com/vscodeshift/mui-snippets
https://marketplace.visualstudio.com/items?itemName=vscodeshift.mui-snippets

**Comment by j3ffx** [comment]
Oh my god thank you @jedwards1211, you are an absolute king !
