### ISSUE TITLE
I dont get any suggestion in js/x files

### ISSUE THREAD

**Issue by sarmancoder** [vscodeshift/material-ui-snippets#51]
Hi, I've downloaded de 3.3.4 version of this extension and I dont get any suggestion as in this gif: https://raw.githubusercontent.com/vscodeshift/material-ui-snippets/master/docs/snippet.gif

I have the 1.60 vscode version and the project I'm working on is fresh...

**Comment by jedwards1211** [comment]
Sorry you're having that issue, for some reason some dependencies didn't get bundled, I'm trying to fix it

**Comment by jedwards1211** [comment]
3.3.3 definitely worked, if you want to downgrade until I get this fixed

**Comment by jedwards1211** [comment]
Okay, it's fixed in 3.3.7 (for me at least, let me know if you have any problems with it)
