### ISSUE TITLE
Improve search result

### ISSUE THREAD

**Issue by oliviertassinari** [vscodeshift/material-ui-snippets#7]
@jcoreio I think that we could make the extension more appealing. The current search result makes me feel this isn't a very well refined extension:

<img width="199" alt="Capture d’écran 2020-03-18 à 12 03 59" src="https://user-images.githubusercontent.com/3165635/76954414-98130d00-6910-11ea-9f03-d1bdb619cfab.png">

What about the following changes?

- Change the name. The name of the extension overflows, we can't see everything. Maybe "Material-UI Snippets" would be better?

<img width="193" alt="Capture d’écran 2020-03-18 à 12 13 13" src="https://user-images.githubusercontent.com/3165635/76955107-deb53700-6911-11ea-90b1-d70a8a131349.png">

- Change the icon. Maybe we could use https://github.com/mui-org/material-ui/blob/master/docs/public/static/logo.png?

<img width="191" alt="Capture d’écran 2020-03-18 à 12 14 18" src="https://user-images.githubusercontent.com/3165635/76955204-0a382180-6912-11ea-8fd0-da58ac1a8998.png">

- Change the description. Maybe "Code snippets for Material-UI."?

<img width="191" alt="Capture d’écran 2020-03-18 à 12 15 04" src="https://user-images.githubusercontent.com/3165635/76955244-1fad4b80-6912-11ea-8fd9-9b309a96b295.png">

**Comment by jedwards1211** [comment]
Yeah sounds good!  I wouldn't have wanted to use the logo without permission.

**Comment by oliviertassinari** [comment]
@jedwards1211 Don't forget to publish the updates when you get the time :)

**Comment by jedwards1211** [comment]
Publishing manually, who does that?
I'm joking, I have automated sematic-release publishing set up, but it failed on this merge and I didn't notice.  Need to figure out a way to make it notify me when it fails
